name: nyampah_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  
  http: ^1.2.2
  shared_preferences: ^2.0.15
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  rename: ^3.0.2
  google_maps_flutter: ^2.10.0
  google_places_flutter: ^2.0.9
  geolocator: ^13.0.2
  tutorial_coach_mark: ^1.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Regular.ttf
        - asset: fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: fonts/Inter_24pt-SemiBold.ttf
          weight: 600
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

